import type { Category } from "../types/index.js";

export const CATEGORIES: Category[] = [
  {
    slug: "trending",
    name: "Trending",
    icon: "Whatshot",
    wallhavenTags: [],
    wallhavenCategories: "111",
    wallhavenPurity: "100",
    description: "The hottest wallpapers right now",
  },
  {
    slug: "nature",
    name: "Nature",
    icon: "Park",
    wallhavenTags: ["nature", "landscape", "scenery", "forest", "mountains"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Beautiful natural landscapes",
  },
  {
    slug: "mountains",
    name: "Mountains",
    icon: "Terrain",
    wallhavenTags: ["mountains", "mountain", "peak"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Majestic mountain scenery",
  },
  {
    slug: "forest",
    name: "Forest",
    icon: "Forest",
    wallhavenTags: ["forest", "woods", "trees"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Enchanting forest views",
  },
  {
    slug: "ocean",
    name: "Ocean",
    icon: "Water",
    wallhavenTags: ["ocean", "sea", "water", "waves"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Deep blue ocean wallpapers",
  },
  {
    slug: "waterfalls",
    name: "Waterfalls",
    icon: "WaterfallChart",
    wallhavenTags: ["waterfall", "waterfalls"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Cascading waterfalls",
  },
  {
    slug: "space",
    name: "Space",
    icon: "RocketLaunch",
    wallhavenTags: ["space", "galaxy", "nebula", "stars", "cosmos"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Stunning space imagery",
  },
  {
    slug: "galaxy",
    name: "Galaxy",
    icon: "AutoAwesome",
    wallhavenTags: ["galaxy", "nebula", "milky way"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Galaxies and nebulae",
  },
  {
    slug: "moon",
    name: "Moon",
    icon: "DarkMode",
    wallhavenTags: ["moon", "lunar"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Moon photography",
  },
  {
    slug: "planets",
    name: "Planets",
    icon: "Public",
    wallhavenTags: ["planet", "planets", "mars", "jupiter", "saturn"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Planetary images",
  },
  {
    slug: "cities",
    name: "Cities",
    icon: "LocationCity",
    wallhavenTags: ["city", "cities", "urban", "skyline", "night city"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Urban cityscapes",
  },
  {
    slug: "architecture",
    name: "Architecture",
    icon: "AccountBalance",
    wallhavenTags: ["architecture", "building", "structure"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Stunning architecture",
  },
  {
    slug: "minimal",
    name: "Minimal",
    icon: "Minimize",
    wallhavenTags: ["minimal", "minimalism", "simple", "clean"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Clean minimal designs",
  },
  {
    slug: "abstract",
    name: "Abstract",
    icon: "BubbleChart",
    wallhavenTags: ["abstract", "art", "digital art", "creative"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Abstract art wallpapers",
  },
  {
    slug: "dark",
    name: "Dark",
    icon: "Brightness4",
    wallhavenTags: ["dark", "black", "shadow"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Dark themed wallpapers",
  },
  {
    slug: "amoled",
    name: "AMOLED",
    icon: "Circle",
    wallhavenTags: ["amoled", "black", "oled", "dark background"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Pure black AMOLED wallpapers",
  },
  {
    slug: "cyberpunk",
    name: "Cyberpunk",
    icon: "Memory",
    wallhavenTags: ["cyberpunk", "cyber", "sci-fi", "futuristic", "neon"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Cyberpunk aesthetic",
  },
  {
    slug: "cars",
    name: "Cars",
    icon: "DirectionsCar",
    wallhavenTags: ["car", "cars", "automobile", "vehicle", "sports car"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Automotive wallpapers",
  },
  {
    slug: "motorcycles",
    name: "Motorcycles",
    icon: "TwoWheeler",
    wallhavenTags: ["motorcycle", "motorcycles", "bike", "motorbike"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Motorcycle wallpapers",
  },
  {
    slug: "gaming",
    name: "Gaming",
    icon: "SportsEsports",
    wallhavenTags: ["gaming", "game", "video game", "esports"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Gaming wallpapers",
  },
  {
    slug: "anime",
    name: "Anime",
    icon: "Animation",
    wallhavenTags: ["anime"],
    wallhavenCategories: "010",
    wallhavenPurity: "100",
    description: "Anime wallpapers",
  },
  {
    slug: "technology",
    name: "Technology",
    icon: "Devices",
    wallhavenTags: ["technology", "tech", "computer", "coding"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Tech themed wallpapers",
  },
  {
    slug: "neon",
    name: "Neon",
    icon: "Lightbulb",
    wallhavenTags: ["neon", "glow", "light", "neon lights"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Neon glow wallpapers",
  },
  {
    slug: "rain",
    name: "Rain",
    icon: "Grain",
    wallhavenTags: ["rain", "rainy", "storm", "weather"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Rainy atmosphere wallpapers",
  },
  {
    slug: "sunset",
    name: "Sunset",
    icon: "WbTwilight",
    wallhavenTags: ["sunset", "sunrise", "dawn", "dusk", "golden hour"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Beautiful sunsets",
  },
  {
    slug: "animals",
    name: "Animals",
    icon: "Pets",
    wallhavenTags: ["animal", "animals", "wildlife", "dog", "cat", "lion"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Animal photography",
  },
  {
    slug: "birds",
    name: "Birds",
    icon: "FlutterDash",
    wallhavenTags: ["bird", "birds", "eagle", "owl"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Bird photography",
  },
  {
    slug: "flowers",
    name: "Flowers",
    icon: "LocalFlorist",
    wallhavenTags: ["flower", "flowers", "floral", "blossom"],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Flower photography",
  },
  {
    slug: "desktop",
    name: "Desktop",
    icon: "DesktopWindows",
    wallhavenTags: [],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Wide desktop wallpapers",
  },
  {
    slug: "mobile",
    name: "Mobile",
    icon: "PhoneAndroid",
    wallhavenTags: [],
    wallhavenCategories: "100",
    wallhavenPurity: "100",
    description: "Mobile wallpapers",
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function searchCategories(query: string): Category[] {
  const lower = query.toLowerCase();
  return CATEGORIES.filter(
    (c) =>
      c.name.toLowerCase().includes(lower) ||
      c.slug.includes(lower) ||
      c.description.toLowerCase().includes(lower)
  );
}
