export interface ScoreRule {
  type: "tag" | "resolution" | "favorites" | "views" | "color";
  match: string | number;
  score: number;
}

export const SCORE_BONUSES: ScoreRule[] = [
  { type: "tag", match: "minimal", score: 10 },
  { type: "tag", match: "minimalism", score: 8 },
  { type: "tag", match: "landscape", score: 8 },
  { type: "tag", match: "abstract", score: 7 },
  { type: "tag", match: "geometry", score: 6 },
  { type: "tag", match: "geometric", score: 6 },
  { type: "tag", match: "gradient", score: 5 },
  { type: "tag", match: "dark", score: 4 },
  { type: "tag", match: "amoled", score: 4 },
  { type: "tag", match: "space", score: 5 },
  { type: "tag", match: "nebula", score: 5 },
  { type: "tag", match: "mountain", score: 6 },
  { type: "tag", match: "forest", score: 5 },
  { type: "tag", match: "architecture", score: 6 },
  { type: "tag", match: "monochrome", score: 5 },
  { type: "tag", match: "low poly", score: 5 },
  { type: "tag", match: "isometric", score: 5 },
  { type: "tag", match: "glassmorphism", score: 5 },
  { type: "tag", match: "topographic", score: 4 },
  { type: "tag", match: "fog", score: 4 },
  { type: "tag", match: "mist", score: 4 },
  { type: "tag", match: "origami", score: 4 },
  { type: "tag", match: "paper cut", score: 4 },
  { type: "tag", match: "waves", score: 3 },
  { type: "tag", match: "material", score: 5 },
  { type: "tag", match: "scandinavian", score: 5 },
  { type: "tag", match: "clean", score: 4 },
  { type: "tag", match: "simple", score: 4 },
  { type: "tag", match: "modern", score: 4 },
  { type: "tag", match: "smooth", score: 3 },
  { type: "tag", match: "soft", score: 3 },
  { type: "tag", match: "calm", score: 4 },
  { type: "tag", match: "peaceful", score: 4 },
  { type: "tag", match: "serene", score: 4 },
  { type: "resolution", match: "3840x2160", score: 6 },
  { type: "resolution", match: "5120x2880", score: 8 },
  { type: "resolution", match: "7680x4320", score: 10 },
  { type: "favorites", match: 1000, score: 8 },
  { type: "favorites", match: 500, score: 5 },
  { type: "favorites", match: 100, score: 2 },
  { type: "views", match: 50000, score: 6 },
  { type: "views", match: 10000, score: 4 },
  { type: "views", match: 1000, score: 2 },
  { type: "color", match: "000000", score: 8 },
  { type: "color", match: "1a1a1a", score: 8 },
  { type: "color", match: "0d0d0d", score: 8 },
  { type: "color", match: "000033", score: 5 },
  { type: "color", match: "000066", score: 5 },
  { type: "color", match: "0066CC", score: 5 },
  { type: "color", match: "0f3460", score: 5 },
  { type: "color", match: "16213e", score: 5 },
  { type: "color", match: "FFFFFF", score: 5 },
  { type: "color", match: "F5F5F5", score: 5 },
  { type: "color", match: "E0E0E0", score: 4 },
  { type: "color", match: "009933", score: 3 },
  { type: "color", match: "336633", score: 3 },
  { type: "color", match: "1a1a2e", score: 5 },
];

export const SCORE_PENALTIES: ScoreRule[] = [
  { type: "tag", match: "anime", score: -Infinity },
  { type: "tag", match: "character", score: -Infinity },
  { type: "tag", match: "girl", score: -Infinity },
  { type: "tag", match: "women", score: -Infinity },
  { type: "tag", match: "people", score: -Infinity },
  { type: "tag", match: "celebrity", score: -Infinity },
  { type: "tag", match: "text", score: -Infinity },
  { type: "tag", match: "logo", score: -Infinity },
  { type: "tag", match: "meme", score: -Infinity },
  { type: "tag", match: "car", score: -Infinity },
  { type: "tag", match: "motorcycle", score: -Infinity },
  { type: "tag", match: "weapon", score: -Infinity },
  { type: "tag", match: "nsfw", score: -Infinity },
  { type: "tag", match: "nude", score: -Infinity },
  { type: "tag", match: "sexy", score: -Infinity },
  { type: "tag", match: "bikini", score: -Infinity },
];

export const HERO_MINIMUM_SCORE = 25;
