import {
  Flame,
  TreePine,
  Mountain,
  Trees,
  Droplets,
  Waves,
  Rocket,
  Sparkles,
  Moon,
  Globe,
  Building2,
  Landmark,
  Minus,
  CircleDot,
  Circle,
  Cpu,
  Car,
  Bike,
  Gamepad2,
  Film,
  MonitorSmartphone,
  Lightbulb,
  Wheat,
  Sunset,
  Cat,
  Bird,
  Flower2,
  Monitor,
  Smartphone,
  Image,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Whatshot: Flame,
  Flame,
  Park: TreePine,
  TreePine,
  Terrain: Mountain,
  Mountain,
  Forest: Trees,
  Trees,
  Water: Droplets,
  Droplets,
  WaterfallChart: Waves,
  Waves,
  RocketLaunch: Rocket,
  Rocket,
  AutoAwesome: Sparkles,
  Sparkles,
  DarkMode: Moon,
  Moon,
  Public: Globe,
  Globe,
  LocationCity: Building2,
  Building2,
  AccountBalance: Landmark,
  Landmark,
  Minimize: Minus,
  Minus,
  BubbleChart: CircleDot,
  CircleDot,
  Brightness4: Moon,
  Circle,
  Memory: Cpu,
  Cpu,
  DirectionsCar: Car,
  Car,
  TwoWheeler: Bike,
  Bike,
  SportsEsports: Gamepad2,
  Gamepad2,
  Animation: Film,
  Film,
  Devices: MonitorSmartphone,
  MonitorSmartphone,
  Lightbulb,
  Wheat,
  WbTwilight: Sunset,
  Sunset,
  Pets: Cat,
  Cat,
  FlutterDash: Bird,
  Bird,
  LocalFlorist: Flower2,
  Flower2,
  DesktopWindows: Monitor,
  Monitor,
  PhoneAndroid: Smartphone,
  Smartphone,
};

export function getCategoryIcon(iconName: string): LucideIcon {
  return iconMap[iconName] || Image;
}
