import {
  Whatshot,
  Park,
  Terrain,
  Forest,
  Water,
  WaterfallChart,
  RocketLaunch,
  AutoAwesome,
  DarkMode,
  Public,
  LocationCity,
  AccountBalance,
  Minimize,
  BubbleChart,
  Brightness4,
  Circle,
  Memory,
  DirectionsCar,
  TwoWheeler,
  SportsEsports,
  Animation,
  Devices,
  Lightbulb,
  Grain,
  WbTwilight,
  Pets,
  FlutterDash,
  LocalFlorist,
  DesktopWindows,
  PhoneAndroid,
  Image,
  type SvgIconComponent,
} from "@mui/icons-material";

const iconMap: Record<string, SvgIconComponent> = {
  Whatshot,
  Park,
  Terrain,
  Forest,
  Water,
  WaterfallChart,
  RocketLaunch,
  AutoAwesome,
  DarkMode,
  Public,
  LocationCity,
  AccountBalance,
  Minimize,
  BubbleChart,
  Brightness4,
  Circle,
  Memory,
  DirectionsCar,
  TwoWheeler,
  SportsEsports,
  Animation,
  Devices,
  Lightbulb,
  Grain,
  WbTwilight,
  Pets,
  FlutterDash,
  LocalFlorist,
  DesktopWindows,
  PhoneAndroid,
};

export function getCategoryIcon(iconName: string): SvgIconComponent {
  return iconMap[iconName] || Image;
}
